pipeline {
    agent any

    tools{
        nodejs 'NodeJs15'
    }
    options {
        timeout(time: 3, unit: 'MINUTES')
    }

    stages {
        stage('Install dependencies') {
            steps {
                sh 'cd ExpressTs && npm install && npx webpack'
            }
        }
        stage('Build dist') {
            steps {
                sh 'cd ExpressTs && npx webpack'
            }
        }
        stage('Run tests') {
            steps {
                sh 'cd ExpressTs && npm test'
            }
        }
    }
}
